# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 715d76cab96b07136d366eb06c48e0e015898af5235bafb04224bd0ff1a3808fb942653a0ee213065cbd7b72c3e6642eab29a21850c52c1e606bfe3bcdfa90ea
  stripe_publishable_key: pk_test_Mm92nd7N9YmkZEmpgJ4VQ0ap
  stripe_secret_key: sk_test_oMTFGbQdxWvZjCgk7AmLmNk6

test:
  secret_key_base: 715d76cab96b07136d366eb06c48e0e015898af5235bafb04224bd0ff1a3808fb942653a0ee213065cbd7b72c3e6642eab29a21850c52c1e606bfe3bcdfa90ea
  stripe_publishable_key: pk_test_Mm92nd7N9YmkZEmpgJ4VQ0ap
  stripe_secret_key: sk_test_oMTFGbQdxWvZjCgk7AmLmNk6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: dcb14eed30fac297b8c745504a719e5079ddf25ea7f97721916400b92b0029b1b904f87b464dc8afeceb49f8bf50983af0754e6cd72a7489b0c4e16464f33e9e
