# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16d231eb7e36323dba1a919c20fb8bb9fa6bc38054ae9772d040fdbd0983e8583ef74865effe3e8470c26f8a6848e63b70c36a0bb462d4f0e115b7cc00d63e3d
  stripe_publishable_key: pk_test_td92pKl0MUz7pNxyQ1XDLWA5
  stripe_secret_key: sk_test_rArybBLs4S4TCl1UycbCmGgE

test:
  secret_key_base: f1760d5200bbc16eccbb9e45fb1256f498c57193baabcca7e2cb991d718119b9ff8b073cc7dd75cd17cefd426a6e892ec093fd1ed3dbf6128dce020bb42fcdfe
  stripe_publishable_key: pk_test_td92pKl0MUz7pNxyQ1XDLWA5
  stripe_secret_key: sk_test_rArybBLs4S4TCl1UycbCmGgE
  
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
